export type FoodCategory = "protein" | "carb" | "fat" | "vegetable";

export type LibraryCategory =
  | "proteinas"
  | "lacteos"
  | "cereales-panes-harinas"
  | "legumbres"
  | "verduras"
  | "bebidas-funcionales"
  | "frutas"
  | "semillas-extras"
  | "aceites-grasas"
  | "condimentos"
  | "otros";

export type MealTag = "breakfast" | "lunch" | "dinner" | "snack";

export type FoodItem = {
  id: string;
  name: string;
  category: FoodCategory;
  libraryCategory: LibraryCategory;
  macroPer100g: number;
  macroName: "protein" | "carbs" | "fats";
  measureName?: string;
  gramsPerMeasure?: number;
  note?: string;
  usageTip?: string;
  benefits?: string[];
  mealTags: MealTag[];
};

export const foodDatabase: FoodItem[] = [
  // PROTEÍNAS
  {
  id: "whole-egg",
  name: "Huevos",
  category: "protein",
  libraryCategory: "proteinas",
  macroPer100g: 12,
  macroName: "protein",
  measureName: "huevo grande",
  gramsPerMeasure: 50,

  note: "También aportan grasa saludable.",

  usageTip:
    "Funciona mejor como complemento. Si la porción se ve muy alta, combínalo con otra proteína principal.",

  benefits: ["Proteína", "Colina", "Saciedad"],
  mealTags: ["breakfast", "dinner", "snack"],
},
  {
    id: "chicken-breast",
    name: "Pechuga de pollo",
    category: "protein",
    libraryCategory: "proteinas",
    macroPer100g: 31,
    macroName: "protein",
    measureName: "palma mediana cocida",
    gramsPerMeasure: 110,
    note: "Peso cocido.",
    benefits: ["Proteína", "Meal prep", "Saciedad"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "chicken-thigh",
    name: "Muslos de pollo",
    category: "protein",
    libraryCategory: "proteinas",
    macroPer100g: 25,
    macroName: "protein",
    measureName: "muslo mediano cocido",
    gramsPerMeasure: 100,
    note: "Útiles para caldos. Aportan más grasa que la pechuga.",
    benefits: ["Proteína", "Caldo", "Saciedad"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "lean-ground-beef",
    name: "Carne molida magra",
    category: "protein",
    libraryCategory: "proteinas",
    macroPer100g: 26,
    macroName: "protein",
    measureName: "palma mediana cocida",
    gramsPerMeasure: 110,
    note: "Puede variar según el porcentaje de grasa.",
    benefits: ["Proteína", "Hierro", "Saciedad"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "beef-fillet",
    name: "Carne en filete (bistec)",
    category: "protein",
    libraryCategory: "proteinas",
    macroPer100g: 27,
    macroName: "protein",
    measureName: "filete mediano cocido",
    gramsPerMeasure: 150,
    benefits: ["Proteína", "Hierro", "Creatina natural"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "girello",
    name: "Solomo redondo / Girello",
    category: "protein",
    libraryCategory: "proteinas",
    macroPer100g: 28,
    macroName: "protein",
    measureName: "palma mediana cocida",
    gramsPerMeasure: 110,
    note: "Ideal para sudado.",
    benefits: ["Proteína", "Bajo en grasa", "Hierro"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "shredded-beef",
    name: "Falda para carne desmechada",
    category: "protein",
    libraryCategory: "proteinas",
    macroPer100g: 26,
    macroName: "protein",
    measureName: "taza cocida",
    gramsPerMeasure: 140,
    benefits: ["Proteína", "Versátil", "Meal prep"],
    mealTags: ["breakfast", "lunch", "dinner"],
  },
  {
    id: "pork-chop",
    name: "Chuleta de cerdo",
    category: "protein",
    libraryCategory: "proteinas",
    macroPer100g: 26,
    macroName: "protein",
    measureName: "chuleta mediana cocida",
    gramsPerMeasure: 140,
    note: "Opcional. Puede aportar más grasa según el corte.",
    benefits: ["Proteína", "Saciedad"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "pork-shoulder",
    name: "Chicharrón / hombro de cerdo",
    category: "protein",
    libraryCategory: "proteinas",
    macroPer100g: 25,
    macroName: "protein",
    measureName: "palma mediana",
    gramsPerMeasure: 110,
    note: "Aporta más grasa. Usar según indicaciones del plan.",
    benefits: ["Proteína", "Saciedad"],
    mealTags: ["lunch", "dinner"],
  },
  {
  id: "chorizo-casero",
  name: "Chorizo casero (del taller de cocina)",
  category: "protein",
  libraryCategory: "proteinas",
  macroPer100g: 18,
  macroName: "protein",
  measureName: "unidad",
  gramsPerMeasure: 80,
  note: "Aporta proteína y grasa. Utilizar las porciones recomendadas por el taller de cocina MonyFit.",
  benefits: ["Proteína", "Saciedad", "Sabor"],
  mealTags: ["breakfast", "lunch", "dinner"],
},
  {
    id: "salmon",
    name: "Salmón",
    category: "protein",
    libraryCategory: "proteinas",
    macroPer100g: 25,
    macroName: "protein",
    measureName: "filete pequeño cocido",
    gramsPerMeasure: 120,
    note: "También aporta grasas saludables.",
    benefits: ["Omega 3", "Proteína", "Vitamina D"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "tuna",
    name: "Atún",
    category: "protein",
    libraryCategory: "proteinas",
    macroPer100g: 26,
    macroName: "protein",
    measureName: "lata escurrida",
    gramsPerMeasure: 100,
    note: "El peso escurrido cambia según la marca.",
    benefits: ["Proteína", "Práctico"],
    mealTags: ["breakfast", "lunch", "dinner", "snack"],
  },
  {
    id: "tofu",
    name: "Tofu natural",
    category: "protein",
    libraryCategory: "proteinas",
    macroPer100g: 14,
    macroName: "protein",
    measureName: "bloque pequeño",
    gramsPerMeasure: 100,
    benefits: ["Proteína vegetal", "Calcio"],
    mealTags: ["lunch", "dinner"],
  },

  // LÁCTEOS Y ALTERNATIVAS
  {
    id: "mozzarella",
    name: "Queso mozzarella",
    category: "protein",
    libraryCategory: "lacteos",
    macroPer100g: 22,
    macroName: "protein",
    measureName: "tajada",
    gramsPerMeasure: 30,

    note: "También aporta grasa. Preferir reducido en grasa si aplica.",

    usageTip:
    "Funciona mejor como complemento. Si la porción se ve muy alta, combínalo con otra proteína principal.",

    benefits: ["Calcio", "Proteína"],
    mealTags: ["breakfast", "snack", "dinner"],
  },
  {
    id: "parmesan",
    name: "Queso parmesano",
    category: "fat",
    libraryCategory: "lacteos",
    macroPer100g: 29,
    macroName: "fats",
    measureName: "cucharada",
    gramsPerMeasure: 10,
      note: "Usar como complemento por su sabor intenso.",
    benefits: ["Calcio", "Sabor"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "greek-yogurt",
    name: "Yogurt griego natural",
    category: "protein",
    libraryCategory: "lacteos",
    macroPer100g: 10,
    macroName: "protein",
    measureName: "taza",
    gramsPerMeasure: 200,

     note: "Funciona mejor como complemento. Si la porción se ve muy alta, combínalo con otra proteína principal.",

usageTip:
    "Funciona mejor como complemento. Si la porción se ve muy alta, combínalo con otra proteína principal.",

    benefits: ["Proteína", "Calcio", "Probióticos"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "coconut-yogurt",
    name: "Yogurt de coco",
    category: "fat",
    libraryCategory: "lacteos",
    macroPer100g: 8,
    macroName: "fats",
    measureName: "taza",
    gramsPerMeasure: 200,
    note: "Revisar etiqueta; algunas marcas tienen azúcar añadida.",
    benefits: ["Alternativa láctea", "Saciedad"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "almond-milk",
    name: "Leche de almendra sin azúcar",
    category: "fat",
    libraryCategory: "lacteos",
    macroPer100g: 1,
    macroName: "fats",
    measureName: "taza",
    gramsPerMeasure: 250,
    note: "Opcional. Elegir sin azúcar.",
    benefits: ["Baja en calorías", "Práctica"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "coconut-milk",
    name: "Leche de coco",
    category: "fat",
    libraryCategory: "lacteos",
    macroPer100g: 7,
    macroName: "fats",
    measureName: "taza",
    gramsPerMeasure: 200,
    note: "Aporta grasa. Revisar etiqueta.",
    benefits: ["Grasas", "Sabor"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "coconut-cream",
    name: "Crema de coco",
    category: "fat",
    libraryCategory: "lacteos",
    macroPer100g: 20,
    macroName: "fats",
    measureName: "cucharada",
    gramsPerMeasure: 15,
    note: "Alta en grasa. Usar con medida.",
    benefits: ["Sabor", "Saciedad"],
    mealTags: ["breakfast", "snack"],
  },

  // CEREALES / PANES / HARINAS
  {
    id: "corn-flour-pan",
    name: "Harina PAN",
    category: "carb",
    libraryCategory: "cereales-panes-harinas",
    macroPer100g: 76,
    macroName: "carbs",
    measureName: "1/2 taza seca",
    gramsPerMeasure: 60,
    note: "Peso seco antes de preparar.",
    benefits: ["Energía", "Versátil"],
    mealTags: ["breakfast", "lunch", "dinner"],
  },
  {
    id: "almond-flour",
    name: "Harina de almendra",
    category: "fat",
    libraryCategory: "cereales-panes-harinas",
    macroPer100g: 50,
    macroName: "fats",
    measureName: "1/4 taza",
    gramsPerMeasure: 28,
    note: "Aporta grasa y proteína. No equivale a harina PAN.",
    benefits: ["Grasas saludables", "Baja en carbos"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "wholegrain-bread",
    name: "Pan integral tajado",
    category: "carb",
    libraryCategory: "cereales-panes-harinas",
    macroPer100g: 43,
    macroName: "carbs",
    measureName: "tajada",
    gramsPerMeasure: 35,
    benefits: ["Energía", "Práctico"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "rice-cakes",
    name: "Galletas de arroz",
    category: "carb",
    libraryCategory: "cereales-panes-harinas",
    macroPer100g: 80,
    macroName: "carbs",
    measureName: "galleta",
    gramsPerMeasure: 9,
    benefits: ["Práctico", "Ligero"],
    mealTags: ["snack", "breakfast"],
  },
  {
    id: "corn-cakes",
    name: "Galletas de maíz",
    category: "carb",
    libraryCategory: "cereales-panes-harinas",
    macroPer100g: 80,
    macroName: "carbs",
    measureName: "galleta",
    gramsPerMeasure: 9,
    benefits: ["Práctico", "Ligero"],
    mealTags: ["snack", "breakfast"],
  },
  {
    id: "wholegrain-wrap",
    name: "Tortillas / wraps integrales",
    category: "carb",
    libraryCategory: "cereales-panes-harinas",
    macroPer100g: 50,
    macroName: "carbs",
    measureName: "wrap mediano",
    gramsPerMeasure: 45,
    benefits: ["Práctico", "Energía"],
    mealTags: ["breakfast", "lunch", "dinner"],
  },
  {
    id: "rice",
    name: "Arroz cocido",
    category: "carb",
    libraryCategory: "cereales-panes-harinas",
    macroPer100g: 28,
    macroName: "carbs",
    measureName: "taza cocida",
    gramsPerMeasure: 155,
    note: "Medir ya preparado.",
    benefits: ["Energía", "Post entreno"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "oats",
    name: "Avena en hojuelas",
    category: "carb",
    libraryCategory: "cereales-panes-harinas",
    macroPer100g: 66,
    macroName: "carbs",
    measureName: "taza seca",
    gramsPerMeasure: 80,
    benefits: ["Fibra", "Energía", "Saciedad"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "granola",
    name: "Granola casera",
    category: "carb",
    libraryCategory: "cereales-panes-harinas",
    macroPer100g: 64,
    macroName: "carbs",
    measureName: "1/2 taza",
    gramsPerMeasure: 45,
    note: "Preferir casera o sin azúcar añadida.",
    benefits: ["Energía", "Práctica"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "pasta",
    name: "Pasta cocida",
    category: "carb",
    libraryCategory: "cereales-panes-harinas",
    macroPer100g: 25,
    macroName: "carbs",
    measureName: "taza cocida",
    gramsPerMeasure: 140,
    note: "Medir ya preparada.",
    benefits: ["Energía", "Rendimiento"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "quinoa",
    name: "Quinoa cocida",
    category: "carb",
    libraryCategory: "cereales-panes-harinas",
    macroPer100g: 21,
    macroName: "carbs",
    measureName: "taza cocida",
    gramsPerMeasure: 185,
    benefits: ["Fibra", "Magnesio", "Energía"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "potato",
    name: "Papa cocida",
    category: "carb",
    libraryCategory: "cereales-panes-harinas",
    macroPer100g: 20,
    macroName: "carbs",
    measureName: "papa mediana",
    gramsPerMeasure: 170,
    benefits: ["Potasio", "Saciedad", "Energía"],
    mealTags: ["lunch", "dinner"],
  },
  {
  id: "mashed-potato",
  name: "Puré de papas",
  category: "carb",
  libraryCategory: "cereales-panes-harinas",
  macroPer100g: 20,
  macroName: "carbs",
  measureName: "taza",
  gramsPerMeasure: 210,
  note: "Puede variar según si se prepara con leche, mantequilla o aceite.",
  benefits: ["Potasio", "Saciedad", "Energía"],
  mealTags: ["lunch", "dinner"],
},
  {
    id: "cassava",
    name: "Yuca cocida",
    category: "carb",
    libraryCategory: "cereales-panes-harinas",
    macroPer100g: 38,
    macroName: "carbs",
    measureName: "trozo mediano",
    gramsPerMeasure: 120,
    benefits: ["Energía", "Saciedad"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "arepa",
    name: "Arepa",
    category: "carb",
    libraryCategory: "cereales-panes-harinas",
    macroPer100g: 45,
    macroName: "carbs",
    measureName: "arepa mediana",
    gramsPerMeasure: 100,
    benefits: ["Energía", "Versátil"],
    mealTags: ["breakfast", "lunch", "dinner"],
  },
  {
  id: "tostones",
  name: "Tostones",
  category: "carb",
  libraryCategory: "cereales-panes-harinas",
  macroPer100g: 31,
  macroName: "carbs",
  measureName: "tostón mediano",
  gramsPerMeasure: 30,
  note: "El valor puede variar según el tamaño y la cantidad de aceite utilizada en la preparación.",
  benefits: ["Energía", "Potasio", "Saciedad"],
  mealTags: ["lunch", "dinner"],
},

  // LEGUMBRES
  {
    id: "lentils",
    name: "Lentejas",
    category: "carb",
    libraryCategory: "legumbres",
    macroPer100g: 20,
    macroName: "carbs",
    measureName: "taza cocida",
    gramsPerMeasure: 180,
    note: "También aportan proteína vegetal.",
    benefits: ["Fibra", "Hierro", "Saciedad"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "chickpeas",
    name: "Garbanzos",
    category: "carb",
    libraryCategory: "legumbres",
    macroPer100g: 27,
    macroName: "carbs",
    measureName: "taza cocida",
    gramsPerMeasure: 165,
    note: "También aportan proteína vegetal.",
    benefits: ["Fibra", "Saciedad", "Proteína vegetal"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "beans",
    name: "Frijoles",
    category: "carb",
    libraryCategory: "legumbres",
    macroPer100g: 24,
    macroName: "carbs",
    measureName: "taza cocida",
    gramsPerMeasure: 170,
    note: "También aportan proteína vegetal.",
    benefits: ["Fibra", "Hierro", "Saciedad"],
    mealTags: ["lunch", "dinner"],
  },

  // VERDURAS
  {
    id: "tomato",
    name: "Tomate",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 4,
    macroName: "carbs",
    measureName: "tomate mediano",
    gramsPerMeasure: 120,
    benefits: ["Vitamina C", "Antioxidantes"],
    mealTags: ["breakfast", "lunch", "dinner"],
  },
  {
    id: "cherry-tomato",
    name: "Tomate cherry",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 4,
    macroName: "carbs",
    measureName: "taza",
    gramsPerMeasure: 150,
    benefits: ["Vitamina C", "Volumen"],
    mealTags: ["lunch", "dinner", "snack"],
  },
  {
    id: "white-onion",
    name: "Cebolla blanca",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 9,
    macroName: "carbs",
    measureName: "1/2 cebolla",
    gramsPerMeasure: 55,
    benefits: ["Sabor", "Fibra"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "red-onion",
    name: "Cebolla morada",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 9,
    macroName: "carbs",
    measureName: "1/2 cebolla",
    gramsPerMeasure: 55,
    benefits: ["Sabor", "Antioxidantes"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "garlic",
    name: "Ajo",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 33,
    macroName: "carbs",
    measureName: "diente",
    gramsPerMeasure: 3,
    benefits: ["Sabor", "Antioxidantes"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "celery",
    name: "Apio",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 3,
    macroName: "carbs",
    measureName: "tallo",
    gramsPerMeasure: 40,
    benefits: ["Hidratación", "Volumen"],
    mealTags: ["lunch", "dinner", "snack"],
  },
  {
    id: "carrot",
    name: "Zanahoria",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 10,
    macroName: "carbs",
    measureName: "zanahoria mediana",
    gramsPerMeasure: 70,
    benefits: ["Vitamina A", "Fibra"],
    mealTags: ["lunch", "dinner", "snack"],
  },
  {
    id: "spinach",
    name: "Espinaca",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 4,
    macroName: "carbs",
    measureName: "taza",
    gramsPerMeasure: 30,
    benefits: ["Hierro", "Folato", "Volumen"],
    mealTags: ["breakfast", "lunch", "dinner"],
  },
  {
    id: "lettuce",
    name: "Lechuga",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 3,
    macroName: "carbs",
    measureName: "taza",
    gramsPerMeasure: 40,
    benefits: ["Volumen", "Hidratación"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "cucumber",
    name: "Pepino",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 3,
    macroName: "carbs",
    measureName: "pepino pequeño",
    gramsPerMeasure: 200,
    benefits: ["Hidratación", "Volumen"],
    mealTags: ["lunch", "dinner", "snack"],
  },
  {
    id: "bell-pepper",
    name: "Pimentón",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 6,
    macroName: "carbs",
    measureName: "pimentón mediano",
    gramsPerMeasure: 120,
    benefits: ["Vitamina C", "Sabor"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "cabbage",
    name: "Col / repollo",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 6,
    macroName: "carbs",
    measureName: "taza picada",
    gramsPerMeasure: 90,
    benefits: ["Fibra", "Volumen"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "green-onion",
    name: "Cebollín",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 7,
    macroName: "carbs",
    measureName: "tallo",
    gramsPerMeasure: 15,
    benefits: ["Sabor", "Frescura"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "cilantro",
    name: "Cilantro",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 4,
    macroName: "carbs",
    measureName: "puñado",
    gramsPerMeasure: 15,
    benefits: ["Sabor", "Frescura"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "parsley",
    name: "Perejil",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 6,
    macroName: "carbs",
    measureName: "puñado",
    gramsPerMeasure: 15,
    benefits: ["Sabor", "Vitamina C"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "basil",
    name: "Albahaca",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 3,
    macroName: "carbs",
    measureName: "puñado",
    gramsPerMeasure: 15,
    benefits: ["Sabor", "Frescura"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "beetroot",
    name: "Remolacha",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 10,
    macroName: "carbs",
    measureName: "unidad pequeña",
    gramsPerMeasure: 80,
    benefits: ["Fibra", "Nitratos naturales"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "radish",
    name: "Rábano",
    category: "vegetable",
    libraryCategory: "verduras",
    macroPer100g: 3,
    macroName: "carbs",
    measureName: "taza",
    gramsPerMeasure: 120,
    benefits: ["Volumen", "Frescura"],
    mealTags: ["lunch", "dinner"],
  },

  // BEBIDAS FUNCIONALES
  {
    id: "dandelion",
    name: "Diente de león",
    category: "vegetable",
    libraryCategory: "bebidas-funcionales",
    macroPer100g: 0,
    macroName: "carbs",
    measureName: "infusión",
    gramsPerMeasure: 250,
    benefits: ["Infusión", "Digestivo"],
    mealTags: ["breakfast", "snack", "dinner"],
  },
  {
    id: "artichoke",
    name: "Alcachofa",
    category: "vegetable",
    libraryCategory: "bebidas-funcionales",
    macroPer100g: 11,
    macroName: "carbs",
    measureName: "infusión",
    gramsPerMeasure: 250,
    benefits: ["Digestivo", "Infusión"],
    mealTags: ["breakfast", "snack", "dinner"],
  },
  {
    id: "ginger",
    name: "Jengibre",
    category: "vegetable",
    libraryCategory: "bebidas-funcionales",
    macroPer100g: 18,
    macroName: "carbs",
    measureName: "trozo pequeño",
    gramsPerMeasure: 5,
    benefits: ["Digestivo", "Sabor", "Infusión"],
    mealTags: ["breakfast", "snack", "dinner"],
  },
  {
    id: "cinnamon-stick",
    name: "Canela en astilla",
    category: "vegetable",
    libraryCategory: "bebidas-funcionales",
    macroPer100g: 80,
    macroName: "carbs",
    measureName: "astilla",
    gramsPerMeasure: 3,
    note: "Cantidad pequeña, impacto calórico mínimo.",
    benefits: ["Sabor", "Infusión"],
    mealTags: ["breakfast", "snack", "dinner"],
  },
  {
    id: "cloves",
    name: "Clavos de olor",
    category: "vegetable",
    libraryCategory: "bebidas-funcionales",
    macroPer100g: 65,
    macroName: "carbs",
    measureName: "unidad",
    gramsPerMeasure: 1,
    note: "Cantidad mínima para infusiones.",
    benefits: ["Sabor", "Infusión"],
    mealTags: ["breakfast", "snack", "dinner"],
  },
  {
    id: "lemon",
    name: "Limón",
    category: "carbs",
    libraryCategory: "frutas",
    macroPer100g: 9,
    macroName: "carbs",
    measureName: "unidad",
    gramsPerMeasure: 60,
    benefits: ["Vitamina C", "Sabor", "Digestivo"],
    mealTags: ["breakfast", "lunch", "dinner", "snack"],
  } as unknown as FoodItem,
  {
    id: "apple-vinegar",
    name: "Vinagre de manzana",
    category: "vegetable",
    libraryCategory: "bebidas-funcionales",
    macroPer100g: 1,
    macroName: "carbs",
    measureName: "cucharadita",
    gramsPerMeasure: 5,
    note: "Opcional.",
    benefits: ["Sabor", "Aderezo"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "mint",
    name: "Menta",
    category: "vegetable",
    libraryCategory: "bebidas-funcionales",
    macroPer100g: 8,
    macroName: "carbs",
    measureName: "hojas",
    gramsPerMeasure: 5,
    benefits: ["Frescura", "Infusión"],
    mealTags: ["breakfast", "snack", "dinner"],
  },

  // FRUTAS
  {
    id: "plantain",
    name: "Plátano maduro",
    category: "carb",
    libraryCategory: "frutas",
    macroPer100g: 31,
    macroName: "carbs",
    measureName: "unidad mediana",
    gramsPerMeasure: 200,
    benefits: ["Energía", "Potasio"],
    mealTags: ["breakfast", "lunch", "dinner"],
  },
  {
    id: "banana",
    name: "Banano",
    category: "carb",
    libraryCategory: "frutas",
    macroPer100g: 23,
    macroName: "carbs",
    measureName: "unidad mediana",
    gramsPerMeasure: 120,
    benefits: ["Potasio", "Energía"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "kiwi",
    name: "Kiwi",
    category: "carb",
    libraryCategory: "frutas",
    macroPer100g: 15,
    macroName: "carbs",
    measureName: "unidad",
    gramsPerMeasure: 75,
    benefits: ["Vitamina C", "Fibra"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "mango",
    name: "Mango",
    category: "carb",
    libraryCategory: "frutas",
    macroPer100g: 15,
    macroName: "carbs",
    measureName: "taza picada",
    gramsPerMeasure: 165,
    benefits: ["Vitamina C", "Energía"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "apple",
    name: "Manzana",
    category: "carb",
    libraryCategory: "frutas",
    macroPer100g: 14,
    macroName: "carbs",
    measureName: "unidad mediana",
    gramsPerMeasure: 180,
    benefits: ["Fibra", "Saciedad"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "pear",
    name: "Pera",
    category: "carb",
    libraryCategory: "frutas",
    macroPer100g: 15,
    macroName: "carbs",
    measureName: "unidad mediana",
    gramsPerMeasure: 180,
    benefits: ["Fibra", "Saciedad"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "mandarin",
    name: "Mandarina",
    category: "carb",
    libraryCategory: "frutas",
    macroPer100g: 13,
    macroName: "carbs",
    measureName: "unidad",
    gramsPerMeasure: 90,
    benefits: ["Vitamina C", "Hidratación"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "strawberries",
    name: "Fresas",
    category: "carb",
    libraryCategory: "frutas",
    macroPer100g: 8,
    macroName: "carbs",
    measureName: "taza",
    gramsPerMeasure: 150,
    benefits: ["Antioxidantes", "Vitamina C", "Fibra"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "blueberries",
    name: "Arándanos",
    category: "carb",
    libraryCategory: "frutas",
    macroPer100g: 14,
    macroName: "carbs",
    measureName: "taza",
    gramsPerMeasure: 150,
    benefits: ["Antioxidantes", "Fibra"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "pineapple",
    name: "Piña",
    category: "carb",
    libraryCategory: "frutas",
    macroPer100g: 13,
    macroName: "carbs",
    measureName: "taza picada",
    gramsPerMeasure: 165,
    benefits: ["Vitamina C", "Digestión"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "orange",
    name: "Naranja",
    category: "carb",
    libraryCategory: "frutas",
    macroPer100g: 12,
    macroName: "carbs",
    measureName: "unidad",
    gramsPerMeasure: 130,
    benefits: ["Vitamina C", "Hidratación"],
    mealTags: ["breakfast", "snack"],
  },

  // SEMILLAS Y EXTRAS
  {
    id: "chia",
    name: "Semillas de chía",
    category: "fat",
    libraryCategory: "semillas-extras",
    macroPer100g: 31,
    macroName: "fats",
    measureName: "cucharada",
    gramsPerMeasure: 12,
    note: "Funciona mejor como complemento. Si la porción se ve muy alta, combínalo con otra proteína principal.",
    benefits: ["Omega 3", "Fibra", "Saciedad"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "flaxseed",
    name: "Linaza molida",
    category: "fat",
    libraryCategory: "semillas-extras",
    macroPer100g: 42,
    macroName: "fats",
    measureName: "cucharada",
    gramsPerMeasure: 10,
    note: "Funciona mejor como complemento. Si la porción se ve muy alta, combínalo con otra proteína principal.",
    benefits: ["Fibra", "Omega 3", "Saciedad"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "almonds",
    name: "Almendras",
    category: "fat",
    libraryCategory: "semillas-extras",
    macroPer100g: 50,
    macroName: "fats",
    measureName: "puñado pequeño",
    gramsPerMeasure: 25,
    benefits: ["Magnesio", "Grasas saludables", "Saciedad"],
    mealTags: ["snack", "breakfast"],
  },
  {
    id: "sunflower-seeds",
    name: "Semillas de girasol",
    category: "fat",
    libraryCategory: "semillas-extras",
    macroPer100g: 51,
    macroName: "fats",
    measureName: "cucharada",
    gramsPerMeasure: 10,
    note: "Funciona mejor como complemento. Si la porción se ve muy alta, combínalo con otra proteína principal.",
    benefits: ["Vitamina E", "Magnesio", "Grasas saludables"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "peanut-butter",
    name: "Mantequilla de maní",
    category: "fat",
    libraryCategory: "semillas-extras",
    macroPer100g: 50,
    macroName: "fats",
    measureName: "cucharada",
    gramsPerMeasure: 16,
    note: "Funciona mejor como complemento. Si la porción se ve muy alta, combínalo con otra proteína principal.",
    benefits: ["Saciedad", "Grasas saludables"],
    mealTags: ["breakfast", "snack"],
  },
  {
    id: "almond-butter",
    name: "Mantequilla de almendra",
    category: "fat",
    libraryCategory: "semillas-extras",
    macroPer100g: 56,
    macroName: "fats",
    measureName: "cucharada",
    gramsPerMeasure: 16,
    note: "Funciona mejor como complemento. Si la porción se ve muy alta, combínalo con otra proteína principal.",
    benefits: ["Grasas saludables", "Magnesio", "Saciedad"],
    mealTags: ["breakfast", "snack"],
  },

  // ACEITES Y GRASAS
  {
    id: "avocado",
    name: "Aguacate",
    category: "fat",
    libraryCategory: "aceites-grasas",
    macroPer100g: 15,
    macroName: "fats",
    measureName: "aguacate mediano",
    gramsPerMeasure: 150,
    benefits: ["Grasas saludables", "Potasio", "Saciedad"],
    mealTags: ["breakfast", "lunch", "dinner"],
  },
  {
    id: "olive-oil",
    name: "Aceite de oliva",
    category: "fat",
    libraryCategory: "aceites-grasas",
    macroPer100g: 100,
    macroName: "fats",
    measureName: "cucharada",
    gramsPerMeasure: 14,
    benefits: ["Grasas saludables", "Antioxidantes"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "avocado-oil",
    name: "Aceite de aguacate",
    category: "fat",
    libraryCategory: "aceites-grasas",
    macroPer100g: 100,
    macroName: "fats",
    measureName: "cucharada",
    gramsPerMeasure: 14,
    benefits: ["Grasas saludables"],
    mealTags: ["lunch", "dinner"],
  },

  // CONDIMENTOS
  {
    id: "salt",
    name: "Sal",
    category: "vegetable",
    libraryCategory: "condimentos",
    macroPer100g: 0,
    macroName: "carbs",
    measureName: "pizca",
    gramsPerMeasure: 1,
    note: "Usar con moderación.",
    benefits: ["Sabor"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "pepper",
    name: "Pimienta",
    category: "vegetable",
    libraryCategory: "condimentos",
    macroPer100g: 64,
    macroName: "carbs",
    measureName: "pizca",
    gramsPerMeasure: 1,
    benefits: ["Sabor"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "paprika",
    name: "Paprika",
    category: "vegetable",
    libraryCategory: "condimentos",
    macroPer100g: 54,
    macroName: "carbs",
    measureName: "cucharadita",
    gramsPerMeasure: 2,
    benefits: ["Sabor", "Color"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "cumin",
    name: "Comino",
    category: "vegetable",
    libraryCategory: "condimentos",
    macroPer100g: 44,
    macroName: "carbs",
    measureName: "cucharadita",
    gramsPerMeasure: 2,
    benefits: ["Sabor"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "garlic-powder",
    name: "Ajo en polvo",
    category: "vegetable",
    libraryCategory: "condimentos",
    macroPer100g: 73,
    macroName: "carbs",
    measureName: "cucharadita",
    gramsPerMeasure: 3,
    benefits: ["Sabor"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "oregano",
    name: "Orégano",
    category: "vegetable",
    libraryCategory: "condimentos",
    macroPer100g: 69,
    macroName: "carbs",
    measureName: "cucharadita",
    gramsPerMeasure: 1,
    benefits: ["Sabor", "Aromático"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "turmeric",
    name: "Cúrcuma",
    category: "vegetable",
    libraryCategory: "condimentos",
    macroPer100g: 65,
    macroName: "carbs",
    measureName: "cucharadita",
    gramsPerMeasure: 3,
    benefits: ["Color", "Sabor"],
    mealTags: ["lunch", "dinner"],
  },
  {
    id: "ginger-powder",
    name: "Jengibre en polvo",
    category: "vegetable",
    libraryCategory: "condimentos",
    macroPer100g: 70,
    macroName: "carbs",
    measureName: "cucharadita",
    gramsPerMeasure: 2,
    benefits: ["Sabor", "Digestivo"],
    mealTags: ["breakfast", "lunch", "dinner"],
  },
  {
    id: "cinnamon",
    name: "Canela",
    category: "vegetable",
    libraryCategory: "condimentos",
    macroPer100g: 80,
    macroName: "carbs",
    measureName: "cucharadita",
    gramsPerMeasure: 2,
    benefits: ["Sabor", "Aromático"],
    mealTags: ["breakfast", "snack"],
  },

  // OTROS
  {
    id: "dark-chocolate",
    name: "Chocolate amargo 70% o mínimo 65%",
    category: "fat",
    libraryCategory: "otros",
    macroPer100g: 43,
    macroName: "fats",
    measureName: "cuadrito",
    gramsPerMeasure: 10,
    note: "Funciona mejor como complemento. Si la porción se ve muy alta, combínalo con otra proteína principal.",
    benefits: ["Antojo dulce", "Antioxidantes"],
    mealTags: ["snack"],
  },
  {
    id: "sugar-free-gelatin",
    name: "Gelatina sin azúcar",
    category: "carb",
    libraryCategory: "otros",
    macroPer100g: 0,
    macroName: "carbs",
    measureName: "porción",
    gramsPerMeasure: 120,
    benefits: ["Antojo dulce", "Baja en calorías"],
    mealTags: ["snack"],
  },
  {
    id: "baking-powder",
    name: "Polvo para hornear",
    category: "vegetable",
    libraryCategory: "otros",
    macroPer100g: 28,
    macroName: "carbs",
    measureName: "cucharadita",
    gramsPerMeasure: 4,
    note: "Uso culinario en pequeñas cantidades.",
    benefits: ["Preparaciones"],
    mealTags: ["breakfast", "snack"],
  },
];