export const tips = [
  // Nutrición
  "Empieza tus comidas por la proteína para mejorar saciedad.",
  "Los vegetales ayudan a dar volumen sin sumar muchas calorías.",
  "No necesitas eliminar carbohidratos para perder grasa.",
  "La proteína en cada comida ayuda a mantener masa muscular.",
  "Planificar tus comidas evita decisiones impulsivas.",
  "Comer lento te ayuda a reconocer mejor la saciedad.",
  "Una comida fuera de plan no arruina tu progreso.",
  "El agua también forma parte de tu estrategia.",
  "Las grasas saludables son importantes, pero también se miden.",
  "La fruta puede ser parte de un plan saludable.",
  "Los carbohidratos son energía, no enemigos.",
  "La constancia pesa más que la perfección.",
  "Medir porciones al inicio te ayuda a aprender visualmente.",
  "Una comida simple también puede ser nutritiva.",
  "Evita llegar con demasiada hambre a la siguiente comida.",
  "Elige alimentos que puedas sostener en tu vida real.",
  "No compenses con castigo; vuelve al plan en la próxima comida.",
  "La comida real suele darte más saciedad que los ultraprocesados.",
  "Un plato balanceado es más fácil de repetir.",
  "Prioriza lo que puedes mantener por semanas, no solo por días.",

  // Hábitos
  "Preparar comida con anticipación reduce el estrés.",
  "Tener opciones listas facilita elegir mejor.",
  "Dormir bien también ayuda a tus resultados.",
  "Caminar más durante el día suma muchísimo.",
  "Tu ambiente influye en tus decisiones.",
  "No esperes motivación para empezar; empieza pequeño.",
  "Una rutina simple hecha todos los días gana.",
  "La disciplina se construye con repetición.",
  "Celebra avances pequeños.",
  "No compares tu proceso con el de otra persona.",
  "Hazlo fácil de repetir.",
  "Tu mejor plan es el que puedes cumplir.",
  "La organización vence a la improvisación.",
  "Si fallas una comida, no falló el día.",
  "Mantén agua cerca durante el día.",
  "Haz compras con una lista.",
  "La preparación empieza antes de tener hambre.",
  "Lo simple también funciona.",
  "Repite comidas que te funcionen.",
  "No necesitas hacerlo perfecto para progresar.",

  // Entrenamiento
  "La fuerza ayuda a moldear tu cuerpo.",
  "Entrenar con intención vale más que entrenar por obligación.",
  "El progreso también ocurre cuando descansas.",
  "Caminar es una herramienta poderosa.",
  "La técnica importa más que levantar pesado.",
  "La constancia en el entrenamiento transforma.",
  "No subestimes los básicos.",
  "Un entrenamiento corto es mejor que ninguno.",
  "El cuerpo necesita recuperación.",
  "La fuerza protege tu masa muscular.",
  "Moverte diariamente ayuda a tu metabolismo.",
  "Entrenar no compensa comer sin control.",
  "La energía mejora cuando comes mejor.",
  "Calentar también forma parte del entrenamiento.",
  "Escucha tu cuerpo sin abandonar tu compromiso.",
  "Tu postura también mejora con fuerza.",
  "La movilidad ayuda a entrenar mejor.",
  "El descanso evita estancamientos.",
  "La intensidad debe ir acompañada de recuperación.",
  "Pequeños progresos siguen siendo progreso.",

  // Mentalidad
  "No estás empezando de cero; estás empezando con experiencia.",
  "Tu proceso no necesita verse perfecto.",
  "La paciencia también es parte del plan.",
  "Tu cuerpo responde a lo que haces repetidamente.",
  "La culpa no construye hábitos.",
  "Elige volver al plan sin drama.",
  "Tu versión saludable también puede disfrutar.",
  "No te hables peor de lo que le hablarías a una amiga.",
  "El progreso real toma tiempo.",
  "Confía en las acciones pequeñas.",
  "La motivación sube y baja; el sistema te sostiene.",
  "Cada comida es una nueva oportunidad.",
  "Tu meta no requiere extremos.",
  "Aprender tus porciones te da libertad.",
  "La comida no es premio ni castigo.",
  "Tu cuerpo merece respeto durante el proceso.",
  "Hazlo por salud, energía y confianza.",
  "La constancia crea identidad.",
  "Lo sostenible siempre gana.",
  "Tu mejor versión se construye hoy.",
];